#!/bin/bash
str=$1
mdtotex $str
sed -i -e 's/\\passthrough{\\lstinline\!\([^!]*\)\!}/\\texttt{\1}/g' \
    -e 's/\\passthrough{\\lstinline"\([^"]*\)"}/\\texttt{\1}/g' \
    -e 's/\\passthrough{\\lstinline'"'"'\([^'"'"']*\)'"'"'}/\\texttt{\1}/g' \
    -e 's/\\passthrough{\\lstinline\*\([^*]*\)\*}/\\texttt{\1}/g' \
    -e 's/\\passthrough{\\lstinline,\([^,]*\),}/\\texttt{\1}/g' \
    ${str%.*}.tex 
lualatex ${str%.*}.tex > /dev/null
rm ${str%.*}.aux ${str%.*}.log ${str%.*}.tex
